### ISSUE TITLE
Adicionar tags no cadastro de receita

### ISSUE THREAD

**Issue by mairieli** [mairieli/recipes-pi#13]
Adicionar apenas o layout com as tags dispostas.
Por padrão, essas tags ficarão "escondidas" (ocultas) na tela. 
Colocar também a opção de mostrar e esconder esses campos na tela.

**Comment by brnomendes** [comment]
**Tags:**
`Micro-ondas` `Forno` `Fogão` `Freezer` `Liquidificador` `Batedeira` `Processador` `Grill` `Sanduicheira` `Cafeteira`
`Colher de café` `Colher de chá` `Colher de sopa` `Garfo` `Copo` `Taça` `Espátula` `Xícara` `Concha` `Descascador de legumes` `Escorredor de macarrão` `Escumadeira` `Faca` `Fouet` `Tigela` `Prato` `Panela` `Panela de Pressão` `Frigideira` `Peneira` `Chaleira` `Ralador` `Funil` `Tábua` `Descascador` `Forma`
